version: '3'
services:
  consul:
    image: hashicorp/consul:1.9.3
    environment:
      - discovery.type=single-node
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
    volumes:
      - consul_data:/consul/data
      - consul_config:/consul/config

volumes:
  consul_data:
  consul_config: