version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data:/usr/share/elasticsearch/data

volumes:
  data: