version: '2'

services:
  redis-sentinel:
    image: bitnami/redis-sentinel
    environment:
      - REDIS_MASTER_HOST=redis
    volumes:
      - redis-sentinel_data:/bitnami
    ports:
      - 26379:26379
  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
    ports:
      - 6379:6379
volumes:
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local